# Generated by Django 3.1.5 on 2021-05-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('グラフタイトル入力', models.CharField(blank=True, max_length=1000)),
                ('要素名入力は要素ごとに空白を入れてください', models.CharField(blank=True, max_length=1000)),
                ('要素数値入力は要素ごとに空白を入れてください', models.CharField(blank=None, max_length=1000)),
                ('x軸ラベル入力', models.CharField(blank=True, max_length=1000)),
                ('y軸ラベル入力', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
