# Generated by Django 3.1.5 on 2021-05-25 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zuapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bougurahu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('グラフ名', models.CharField(blank=True, max_length=1000)),
                ('グラフタイトル', models.CharField(blank=True, max_length=1000)),
                ('グラフ要素_空白くぎりで記入してください', models.TextField(blank=True, max_length=1000)),
                ('グラフ要素の数値_空白区切りで記入してください', models.TextField(blank=True, max_length=1000)),
                ('横軸の名称', models.CharField(blank=True, max_length=1000)),
                ('縦軸の名称', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='engurahu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('グラフ名', models.CharField(blank=True, max_length=1000)),
                ('グラフタイトル', models.CharField(blank=True, max_length=1000)),
                ('グラフ要素_空白くぎりで記入してください', models.TextField(blank=True, max_length=1000)),
                ('グラフ要素の数値_空白区切りで記入してください', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='oresen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('グラフ名', models.CharField(blank=True, max_length=1000)),
                ('グラフタイトル', models.CharField(blank=True, max_length=1000)),
                ('グラフ要素_空白くぎりで記入してください', models.TextField(blank=True, max_length=1000)),
                ('グラフ要素の数値_空白区切りで記入してください', models.TextField(blank=True, max_length=1000)),
                ('横軸の名称', models.CharField(blank=True, max_length=1000)),
                ('縦軸の名称', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='paretozu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('グラフ名', models.CharField(blank=True, max_length=1000)),
                ('グラフタイトル', models.CharField(blank=True, max_length=1000)),
                ('グラフ要素_空白くぎりで記入してください', models.TextField(blank=True, max_length=1000)),
                ('グラフ要素の数値_空白区切りで記入してください', models.TextField(blank=True, max_length=1000)),
                ('横軸の名称', models.CharField(blank=True, max_length=1000)),
                ('縦軸の名称', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
