# Generated by Django 3.1.5 on 2021-05-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zuapp', '0002_bougurahu_engurahu_oresen_paretozu'),
    ]

    operations = [
        migrations.CreateModel(
            name='oresenzu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('グラフ名', models.CharField(blank=True, max_length=1000)),
                ('グラフタイトル', models.CharField(blank=True, max_length=1000)),
                ('数字を入力してください_4月', models.IntegerField(default=0)),
                ('数字を入力してください_5月', models.IntegerField(default=0)),
                ('数字を入力してください_6月', models.IntegerField(default=0)),
                ('数字を入力してください_7月', models.IntegerField(default=0)),
                ('数字を入力してください_8月', models.IntegerField(default=0)),
                ('数字を入力してください_9月', models.IntegerField(default=0)),
                ('数字を入力してください_10月', models.IntegerField(default=0)),
                ('数字を入力してください_11月', models.IntegerField(default=0)),
                ('数字を入力してください_12月', models.IntegerField(default=0)),
                ('数字を入力してください_1月', models.IntegerField(default=0)),
                ('数字を入力してください_2月', models.IntegerField(default=0)),
                ('数字を入力してください_3月', models.IntegerField(default=0)),
                ('横軸の名称', models.CharField(blank=True, max_length=1000)),
                ('縦軸の名称', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
